PANDAS_STR_NA_VALUES_CUSTOMIZED = [
    b'-nan',
    b'',
    b'NaN',
    b'<NA>',
    b'nan',
    b'N/A',
    b'-1.#IND',
    b'1.#QNAN',
    b'-1.#QNAN',
    b'1.#IND',
    b'n/a',
    b'#N/A N/A',
    b'None',
    b'-NaN',
    b'NULL',
    b'#NA',
    b'#N/A',
    b'null',
    # b'NA' removed because of clash with milligram per kilogram (NA), otherwise it is default from pandas
]
