using System.CommandLine;
using UneceGenerator;

var fileOption = new Option<FileInfo>(
    name: "--file",
    description: "Path to the file with the UNECE units JSON.")
{
    IsRequired = true,
};
fileOption.AddAlias("-f");

var rootCommand = new RootCommand("Simple C# Unit classes generator from UNECE JSON file generated by python script.")
{
    fileOption,
};

rootCommand.SetHandler(Generator.Run, fileOption);
return await rootCommand.InvokeAsync(args);