from lib.unit import Unit

STATE = "D"
COMMON_CODE = "TTT"
COMMON_CODE2 = "TT2"
COMMON_CODE3 = "TT3"
NAME = "Test name"
DESCRIPTION = "Test description"
CATEGORY = "1M"
SYMBOL = "mg"
SYMBOL2 = "kg"
SYMBOL3 = "g"
CONVERSION_FACTOR = "1e-3 g"
CONVERSION_FACTOR2 = "1e3 g"
CONVERSION_FACTOR3 = "1 g"
UNIT = Unit.parse(STATE, COMMON_CODE, NAME, DESCRIPTION, CATEGORY, SYMBOL, CONVERSION_FACTOR)
UNIT2 = Unit.parse(STATE, COMMON_CODE2, NAME, DESCRIPTION, CATEGORY, SYMBOL2, CONVERSION_FACTOR)
UNIT3 = Unit.parse(STATE, COMMON_CODE3, NAME, DESCRIPTION, CATEGORY, SYMBOL3, CONVERSION_FACTOR)
