# .github/workflows/dotnet-tests.yml
name: .NET Tests

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      
      configuration:
        required: false
        default: "Release"
        type: string


jobs:
  dotnet-tests:
    runs-on: "ubuntu-latest"
    name: Run .NET tests
    steps:
      - uses: actions/checkout@v4
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4

      - name: Build whole solution
        working-directory: ${{ inputs.working-directory }}
        run: |
          dotnet build --configuration ${{ inputs.configuration }}

      - name: Test with dotnet test
        working-directory: ${{ inputs.working-directory }}
        run: |
          dotnet test --no-restore --configuration ${{ inputs.configuration }}