name: Pull actions

on:
  pull_request:

jobs:
  python-tests:
    runs-on: "ubuntu-latest"
    name: Run Python tests
    env:
      WORKING_DIRECTORY: "python"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --editable ./src/unece_excel_parser[dev]
      - name: Test with pytest
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          pytest